version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: Install cependencies
          command: npm ci
      - run:
          name: Lint code
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm t
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Commons.host authenticate
          command: npx commonshost signin --username ${COMMONSHOST_USERNAME} --password ${COMMONSHOST_PASSWORD}
      - run:
          name: Deploy
          command: npm run deploy
